In [3]:
#Python program to perform all matrix operations using numpy
import numpy as np
x=np.array([[7,2,4],[3,4,5],[33,6,7]])
y=np.array([[7,22,5],[5,44,3],[3,2,1]])
print("Addition of two matrices : ")
print(np.add(x,y))
print("Subtraction of two matrices : ")
print(np.subtract(x,y))
print("Multiplication of two matrices : ")
print(np.multiply(x,y))
print("Division of two matrices : ")
print(np.divide(x,y))
print("Product of two matrices : ")
print(np.dot(x,y))
print("Square root of a matrix : ")
print(np.sqrt(x))
print("Summation of column wise elements: ")
print(np.sum(y,axis=0))
print("Summation of row wise matrix : ")
print(np.sum(y,axis=1))
print("Transpose of matrix : ")
print(x.T)

Addition of two matrices : 
[[14 24  9]
 [ 8 48  8]
 [36  8  8]]
Subtraction of two matrices : 
[[  0 -20  -1]
 [ -2 -40   2]
 [ 30   4   6]]
Multiplication of two matrices : 
[[ 49  44  20]
 [ 15 176  15]
 [ 99  12   7]]
Division of two matrices : 
[[ 1.          0.09090909  0.8       ]
 [ 0.6         0.09090909  1.66666667]
 [11.          3.          7.        ]]
Product of two matrices : 
[[  71  250   45]
 [  56  252   32]
 [ 282 1004  190]]
Square root of a matrix : 
[[2.64575131 1.41421356 2.        ]
 [1.73205081 2.         2.23606798]
 [5.74456265 2.44948974 2.64575131]]
Summation of column wise elements: 
[15 68  9]
Summation of row wise matrix : 
[34 52  6]
Transpose of matrix : 
[[ 7  3 33]
 [ 2  4  6]
 [ 4  5  7]]


In [4]:
#Perform SVD (Singular Value Decomposition using python)
from numpy import array
from scipy.linalg import svd
A=array([[1,2],[3,4],[5,6],[10,8]])
print(A)
U,s,VT=svd(A)
print(U)
print(s)
print(VT)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [10  8]]
[[-0.13229621 -0.42605967 -0.48115926 -0.75462351]
 [-0.31048578 -0.47327257 -0.51061143  0.64721528]
 [-0.48867536 -0.52048548  0.6971847  -0.06499811]
 [-0.80454502  0.56884189 -0.14729299 -0.08620317]]
[15.86589447  1.80925193]
[[-0.72813925 -0.68542923]
 [ 0.68542923 -0.72813925]]
